<?php
/*******************************************************************************************
*   ___  _          ______                     _ _                _                        *
*  / _ \| |         | ___ \                   | (_)              | |              © 2020   *
* / /_\ | | _____  _| |_/ /_ __ __ _ _ __   __| |_ _ __   __ _   | |_ ___  __ _ _ __ ___   *
* |  _  | |/ _ \ \/ / ___ \ '__/ _` | '_ \ / _` | | '_ \ / _` |  | __/ _ \/ _` | '_ ` _ \  *
* | | | | |  __/>  <| |_/ / | | (_| | | | | (_| | | | | | (_| |  | ||  __/ (_| | | | | | | *
* \_| |_/_|\___/_/\_\____/|_|  \__,_|_| |_|\__,_|_|_| |_|\__, |  \___\___|\__,_|_| |_| |_| *
*                                                         __/ |                            *
*                                                        |___/                             *
* ---------------------------------------------------------------------------------------- *
* This is commercial software, only users who have purchased a valid license and accept    *
* to the terms of the License Agreement can install and use this program.                  *
* ---------------------------------------------------------------------------------------- *
* website: https://cs-cart.alexbranding.com                                                *
*   email: info@alexbranding.com                                                           *
*******************************************************************************************/
if (!defined('BOOTSTRAP')) {
die('Access denied');}
use Tygh\Registry;if (call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'XVV6aGldU2ZoanR1c3o7O2hmdQ==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'c3ZvdWpuZi9ucGVm'))) == call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'YmVlYGBiY2BgbWRgbmZvdg=='))) {
$cid=$_REQUEST[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'ZGJ1Zmhwc3pgamU='))];$i="ABLC-$cid: ";$m=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'ZWNgaGZ1YGdqZm1l')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'VEZNRkRVIUpHT1ZNTSluL25mb3ZgamUtITEqIUdTUE4hQDtuZm92dCFidCFuIUpPT0ZTIUtQSk8hQDtuZm92dGBlZnRkc2pxdWpwb3QhYnQhbmUhUE8hKW4vbmZvdmBqZSE+IW5lL25mb3ZgamUqIVhJRlNGIW5lL29ibmYhbWpsZiFAdCFCT0UhbmUvbWJvaGBkcGVmIT4hQHQhQHEhUFNFRlMhQ1ohbi9uZm92YGplIU1KTkpVITI=')),$i.'%',CART_LANGUAGE,call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Z29gaGZ1YGRwbnFib3pgZHBvZWp1anBv')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'bi9kcG5xYm96YGpl'))));if (empty($m)) {
$m=0;foreach (call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Z29gaGZ1YHVzYm90bWJ1anBvYG1ib2h2YmhmdA=='))) as $md[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'bWJvaGBkcGVm'))]=>$v) {
$md[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'ZHBucWJvemBqZQ=='))]=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Z29gaGZ1YHN2b3VqbmZgZHBucWJvemBqZQ==')));$md[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'bmZvdmBqZQ=='))]=$m;$md[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'b2JuZg=='))]=$i.call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Z29gaGZ1YGRidWZocHN6YHFidWk=')),$cid,$md[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'bWJvaGBkcGVm'))]);$m=Tygh\Menu::update($md);}
call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Z29gdGZ1YG9wdWpnamRidWpwbw==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Tw==')),call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'YGA=')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'b3B1amRm'))),call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'YGA=')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'YmNgYG1kL2JlZWBuZm92L2JlZWZlYG9meGBuZm92'))));} else {
call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Z29gdGZ1YG9wdWpnamRidWpwbw==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'Tw==')),call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'YGA=')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'b3B1amRm'))),call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'YGA=')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'YmNgYG1kL2JlZWBuZm92L3Z0ZmVgZnlqdHVqb2hgbmZvdg=='))));}
call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'ZWNgcnZmc3o=')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3bc`f92bd3````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'e81ac2','',ab_____('f92bd3cbtf75f92bd3`efdpef')),'VlFFQlVGIUA7ZGJ1Zmhwc2pmdCFURlUhYmNgYG1kYG5mb3ZgamUhPiFAaiFYSUZTRiFkYnVmaHBzemBqZSE+IUBq')),$m,$cid);return [CONTROLLER_STATUS_REDIRECT,"categories.update&category_id={$cid}&selected_section=addons"];}
