<?php
/*******************************************************************************************
*   ___  _          ______                     _ _                _                        *
*  / _ \| |         | ___ \                   | (_)              | |              © 2020   *
* / /_\ | | _____  _| |_/ /_ __ __ _ _ __   __| |_ _ __   __ _   | |_ ___  __ _ _ __ ___   *
* |  _  | |/ _ \ \/ / ___ \ '__/ _` | '_ \ / _` | | '_ \ / _` |  | __/ _ \/ _` | '_ ` _ \  *
* | | | | |  __/>  <| |_/ / | | (_| | | | | (_| | | | | | (_| |  | ||  __/ (_| | | | | | | *
* \_| |_/_|\___/_/\_\____/|_|  \__,_|_| |_|\__,_|_|_| |_|\__, |  \___\___|\__,_|_| |_| |_| *
*                                                         __/ |                            *
*                                                        |___/                             *
* ---------------------------------------------------------------------------------------- *
* This is commercial software, only users who have purchased a valid license and accept    *
* to the terms of the License Agreement can install and use this program.                  *
* ---------------------------------------------------------------------------------------- *
* website: https://cs-cart.alexbranding.com                                                *
*   email: info@alexbranding.com                                                           *
*******************************************************************************************/
if (!defined('BOOTSTRAP')) {
die('Access denied');}
use Tygh\Registry;use Tygh\Menu;use Tygh\Languages\Languages;function fn_ab__fn_demodata_add_menus($status='A'){
$path=Registry::get('config.dir.var').call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGVidWIwYmNgYGdidHVgb2J3amhidWpwbzA='));$full_path="{$path}menu/data.json";$data=fn_get_contents($full_path);$str=__(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvL2VmbnBlYnViL2Zzc3BzdC9nam1mYGNzcGxmbw==')),[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'XGdqbWZgcWJ1aV4='))=>$full_path]);if (empty($data)) {
call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Z29gdGZ1YG9wdWpnamRidWpwbw==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Rg==')),__(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'ZnNzcHM='))),$str);return $str;}
$menu=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'a3Rwb2BlZmRwZWY=')),call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'a3Rwb2Bmb2RwZWY=')),call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'a3Rwb2BlZmRwZWY=')),$data)),true);if (empty($menu)) {
call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Z29gdGZ1YG9wdWpnamRidWpwbw==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Rg==')),__(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'ZnNzcHM='))),$str);return $str;}
$menu_name='AB: Fast navigation ('.substr(TIME,-4).')';$menu_data=[
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'b2JuZg=='))=>$menu_name,
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'bWJvaGBkcGVm'))=>DESCR_SL,
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'dHVidXZ0'))=>$status,
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'ZHBucWJvemBqZQ=='))=>call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'XVV6aGldU2ZoanR1c3o7O2hmdQ==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'c3ZvdWpuZi9kcG5xYm96YGpl')))?call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'XVV6aGldU2ZoanR1c3o7O2hmdQ==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'c3ZvdWpuZi9kcG5xYm96YGpl'))):1,
];$menu_id=Menu::update($menu_data);fn_copy($path,fn_get_files_dir_path());$parrents=[];fn_ab__fn_demodata_run_throw_items($path,$menu,$menu_id,$parrents);$str=__('ab__fn.demodata.success.menu_created',[
'[href]'=>fn_url('static_data.manage&section=A&menu_id='.$menu_id,'A'),'[name]'=>$menu_name,
]);call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Z29gdGZ1YG9wdWpnamRidWpwbw==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Tw==')),__(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'b3B1amRm'))),$str);return $str;}
function fn_ab__fn_demodata_run_throw_items($path,$menus,$menu_id,$parrents){
foreach ($menus as $menu) {
foreach ($menu as $m) {
$item=[
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNA=='))=>($m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNA=='))] == call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'RDsxO08=')))?$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNA=='))]:'',
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNg=='))=>$menu_id,
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzZm91YGpl'))=>!empty($parrents[$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzZm91YGpl'))]])?$parrents[$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzZm91YGpl'))]]:0,
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'ZWZ0ZHM='))=>$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'anVmbg=='))],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm4='))=>$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'aXNmZw=='))],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cXB0anVqcG8='))=>$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cXB0anVqcG8='))],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'ZG1idHQ='))=>$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'ZG1idHQ='))],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG5mb3ZgdHVidXZ0'))=>$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG5mb3ZgdHVidXZ0'))],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYHZ0ZmBwc2poam9gam5iaGY='))=>$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYHZ0ZmBwc2poam9gam5iaGY='))],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYHVmeXU='))=>!empty($m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYHVmeXU='))])?$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYHVmeXU='))]:'',
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYGRwbXBz'))=>!empty($m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYGRwbXBz'))])?$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYGRwbXBz'))]:'',
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYGNiZGxoc3B2b2U='))=>!empty($m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYGNiZGxoc3B2b2U='))])?$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG1iY2ZtYGNiZGxoc3B2b2U='))]:'',
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'c3Y='))=>$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'c3Y='))],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'bmZoYmNweQ=='))=>[
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'dXpxZg=='))=>[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNA=='))=>($m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNA=='))] == call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'RDsxO08=')))?$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNA=='))]:''],
call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'dnRmYGp1Zm4='))=>[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gNCghPj8hKFo='))],
],
];$i=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Z29gYmNgYGdvYHZxZWJ1ZmB0dWJ1amRgZWJ1Yg==')),$item);$parrents[$m[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cWJzYm5gamU='))]]=$i;$images=[];$img=call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG5mb3ZgamRwbw=='));$images["{$img}_image_data"]=[[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'dXpxZg=='))=>call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Tg==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'cGNrZmR1YGpl'))=>0,call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'am5iaGZgYm11'))=>'']];$images["file_{$img}_image_icon"]=[!empty($m[$img])?'menu/'.$m[$img]:''];$images["type_{$img}_image_icon"]=[call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'dGZzd2Zz'))];$_REQUEST=call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YnNzYnpgbmZzaGY=')),$_REQUEST,$images);call_user_func(call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'Z29gYnV1YmRpYGpuYmhmYHFianN0')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG5mb3ZgamRwbw==')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75cbc`6bd75c````')),call_user_func(call_user_func(ab_____('tus`sfqmbdf'),'5ac64b','',ab_____('6bd75ccbtf756bd75c`efdpef')),'YmNgYGdvYG5mb3ZgamRwbw==')),$i);}}}
function fn_ab__fn_update_static_data($data,$param_id=0,$section='A',$lang_code=DESCR_SL){
$current_id_path='';$schema=fn_get_schema('static_data','schema');$section_data=$schema[$section];if (!empty($section_data['has_localization'])) {
$data['localization']=empty($data['localization'])?'':fn_implode_localizations($data['localization']);}
if (!empty($data['megabox'])) {
foreach ($data['megabox']['type'] as $p=>$v) {
if (!empty($v)) {
$data[$p]=$v.':'.intval($data[$p][$v]).':'.$data['megabox']['use_item'][$p];} else {
$data[$p]='';}}}
$condition=db_quote('param_id=?i',$param_id);fn_set_hook('update_static_data',$data,$param_id,$condition,$section,$lang_code);if (!empty($param_id)) {
$current_id_path=db_get_field("SELECT id_path FROM ?:static_data WHERE $condition");db_query("UPDATE ?:static_data SET ?u WHERE param_id=?i",$data,$param_id);db_query('UPDATE ?:static_data_descriptions SET ?u WHERE param_id=?i AND lang_code=?s',$data,$param_id,$lang_code);fn_print_die($data,$param_id,$section,$lang_code);} else {
$data['section']=$section;$param_id=$data['param_id']=db_query("INSERT INTO ?:static_data ?e",$data);foreach (Languages::getAll() as $data['lang_code']=>$_v) {
db_query('REPLACE INTO ?:static_data_descriptions ?e',$data);}}
if (isset($data['parent_id'])) {
if (!empty($data['parent_id'])) {
$new_id_path=db_get_field("SELECT id_path FROM ?:static_data WHERE param_id=?i",$data['parent_id']);$new_id_path.='/'.$param_id;} else {
$new_id_path=$param_id;}
if (!empty($current_id_path) && $current_id_path != $new_id_path) {
db_query("UPDATE ?:static_data SET id_path=CONCAT(?s,SUBSTRING(id_path,?i)) WHERE id_path LIKE ?l","$new_id_path/",strlen($current_id_path.'/') + 1,"$current_id_path/%");}
db_query("UPDATE ?:static_data SET id_path=?s WHERE param_id=?i",$new_id_path,$param_id);}
if (!empty($section_data['icon'])) {
fn_attach_image_pairs('static_data_icon',$section_data['icon']['type'],$param_id,$lang_code);}
return $param_id;}